### PR TITLE
koawalib v1.1.0 

### PR DESCRIPTION
**Pull request by neilmehra**
new features:

- Command renamed to Cmd
- KMotorEx completely rewritten with new pid controller and asym motion profiling
- KMotorExTuner for tuning motor pid/ff constants
- infix Cmd scheduling **| tested**
- GVF Simple and FF Controller
- GVFCmd (see GVFController)
- LoopUntilCmd (loops an action until given end condition is reached)
- LoopCmd now extends LoopUntilCmd
- WaitForCmd renamed to WaitUntilCmd
- Groups (Cmd groups were entirely rewritten)
- new custom pid controller instead of using rr's 
- Asymmetrical motion profiles **| tested**
- Debouncer on KTrigger
- KDIstanceSensor rate limited to avoid Rev2m blocking
- Rate limiter  **| tested**
- Speeds class used for representing drive power with conversions (e.g. wheel power to field centric) **| tested**
- Some wpilib classes ported (debouncer, dcmotor, slewratelimiter, units)

internal changes:

- gradle dependency refactor **| tested**
- device registery **| tested**
- voltage sensor integration with device registery
- KScheduler rewritten **| tested**
- Logger smart reset **| tested**
- GVF Controller abstracted away
- Gamepad functionality rewritten (KButton, KAxis, KStick, KTrigger)
- ButtonFunc interface, Button class (impl of ButtonFunc)
- GVFUtil (should make internal)
- Logger somewhat fixed for now **| tested**
- derivative estimation math moved to math util
- extend and projection functions now use vector math instead **| tested**
- KBoolean isn't a fun interface anymore
- Extensions class  **| tested**

### CODE REVIEW

**Comment by neilmehra** [comment]
hopefully @Spanini2 or @TheCoolGuy123 can test the [feature branch](https://github.com/AsianKoala/koawalib/tree/feature-1.1.0) for this pr when you guys next come over.

```implementation 'com.github.AsianKoala:koawalib:feature-1.1.0-SNAPSHOT'```

**Comment by neilmehra** [comment]
- removed direct velocity control from pidcontroller (might add later)
- fixed rate limiter
- fixed logger/added timestamps to logdata print string
- default configs for logger
- wrote some tests

**Comment by neilmehra** [comment]
> hopefully @Spanini2 or @TheCoolGuy123 can test the [feature branch](https://github.com/AsianKoala/koawalib/tree/feature-1.1.0) for this pr when you guys next come over.
> 
> ```implementation 'com.github.AsianKoala:koawalib:feature-1.1.0-SNAPSHOT'```
> 

specifically if @spanini2 or @TheCoolGuy123 could test the new KMotorEx that would be nice. First priority is basic PID, but motion profiling ur turret would be helpful.

**Comment by neilmehra** [comment]
seems like ill never be happy with koawalib to the point of merging this pr at least until school ends.. feelsbad

**Comment by neilmehra** [comment]
at this point just unit test the new KMotor, try using it in https://github.com/ftc-noteam/offseason, and then merge

**Comment by AsianKoala** [comment]
bruh

**Comment by neilmehra** [comment]
tfw this will never get merged because im lazy

**Comment by neilmehra** [comment]
we back

**Comment by neilmehra** [comment]
TODO: check the @ TODO's in the project

**Comment by neilmehra** [comment]
removed Motor class (wpilib clone)

**Comment by neilmehra** [comment]
private val ticksPerUnit = 1892.3724

**Comment by neilmehra** [comment]
omg finally merging wtf??????????

**Comment by neilmehra** [comment]
@TheCoolGuy123 @spanini2 koawalib v1.1.0 has finally merged

**Pull request merged**
